version: "3.9"

services:
  api:
    container_name: fixit-api
    image: node:16.17.0
    ports: ["8080:8080"]
    working_dir: /home/node/app
    user: node
    volumes:
      - ".:/home/node/app:ro"
    env_file:
      - src/server/.dev.env
      # Also .staging.env and .prod.env
    depends_on:
      - dynamodb-local
  dynamodb-local:
    container_name: dynamodb-local
    image: "amazon/dynamodb-local:latest"
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
