import { USER_ID_REGEX_PATTERN_STR } from "../User/regex.js";
import { DELIMITER } from "../_common/delimiter.js";
import { UUID_REGEX_PATTERN_STR } from "../_common/regex.js";

export const WO_SK_PREFIX_STR = "WO";
export const WO_SK_REGEX_PATTERN_STR = `${WO_SK_PREFIX_STR}${DELIMITER}${USER_ID_REGEX_PATTERN_STR}${DELIMITER}${UUID_REGEX_PATTERN_STR}`;
export const WO_SK_REGEX = new RegExp(`^${WO_SK_REGEX_PATTERN_STR}$`);

export const WO_CHECKLIST_ITEM_ID_INFIX_STR = "CHECKLIST_ITEM";
export const WO_CHECKLIST_ITEM_ID_REGEX_PATTERN_STR = `${WO_SK_REGEX_PATTERN_STR}${DELIMITER}${WO_CHECKLIST_ITEM_ID_INFIX_STR}${DELIMITER}${UUID_REGEX_PATTERN_STR}`;
export const WO_CHECKLIST_ITEM_ID_REGEX = new RegExp(`^${WO_CHECKLIST_ITEM_ID_REGEX_PATTERN_STR}$`);
