# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.yaml

openapi: "3.1.0"
info:
  title: Fixit REST API
  version: "2.0.1"
  description: API for Fixit auth and user account management.
  termsOfService: "https://gofixit.app/tos"
  contact:
    name: Trevor Anderson
    email: "Trevor@Nerdware.cloud"
    url: "https://github.com/trevor-anderson"
  license:
    name: Proprietary
    url: "https://raw.githubusercontent.com/Nerdware-LLC/fixit-api/main/LICENSE"
servers:
  - { url: "http://localhost:8080/api", description: Local Dev Server }
  - { url: "https://gofixit.app/api", description: Production API }
  - { url: "https://staging.gofixit.app/api", description: Staging API }
tags:
  - { name: admin, description: Administrative endpoints }
  - { name: auth, description: Authentication endpoints }
  - { name: checkout, description: Checkout-related endpoints }
  - { name: stripe, description: Stripe-related endpoints }
  - { name: stripe-connect, description: StripeConnect-related endpoints }
  - { name: stripe-link, description: Endpoints which return a Stripe link }
  - { name: subscriptions, description: Subscription management endpoints }
paths:
  "/admin/csp-violation": { $ref: "./endpoints/admin.csp-violation.yaml" }
  "/admin/healthcheck": { $ref: "./endpoints/admin.healthcheck.yaml" }
  "/auth/login": { $ref: "./endpoints/auth.login.yaml" }
  "/auth/register": { $ref: "./endpoints/auth.register.yaml" }
  "/auth/token": { $ref: "./endpoints/auth.token.yaml" }
  "/auth/google-token": { $ref: "./endpoints/auth.google-token.yaml" }
  "/connect/account-link": { $ref: "./endpoints/connect.account-link.yaml" }
  "/connect/dashboard-link": { $ref: "./endpoints/connect.dashboard-link.yaml" }
  "/subscriptions/check-promo-code": { $ref: "./endpoints/subscriptions.check-promo-code.yaml" }
  "/subscriptions/customer-portal": { $ref: "./endpoints/subscriptions.customer-portal.yaml" }
  "/subscriptions/submit-payment": { $ref: "./endpoints/subscriptions.submit-payment.yaml" }
components:
  securitySchemes:
    JwtBearerAuth: { $ref: "./securitySchemes/JwtBearerAuth.yaml" }
  requestBodies:
    CheckPromoCodeRequest: { $ref: "./requestBodies/CheckPromoCodeRequest.yaml" }
    GoogleTokenRequest: { $ref: "./requestBodies/GoogleTokenRequest.yaml" }
    LoginRequest: { $ref: "./requestBodies/LoginRequest.yaml" }
    RefreshAuthTokenRequest: { $ref: "./requestBodies/RefreshAuthTokenRequest.yaml" }
    StripeLinkRequest: { $ref: "./requestBodies/StripeLinkRequest.yaml" }
    UserRegistrationRequest: { $ref: "./requestBodies/UserRegistrationRequest.yaml" }
  # prettier-ignore
  responses:
    200AuthToken: { $ref: "./responses/200.AuthToken.yaml" }
    200AuthTokenAndPreFetchedUserItems: { $ref: "./responses/200.AuthTokenAndPreFetchedUserItems.yaml" }
    200AuthTokenAndCheckoutCompletionInfo: { $ref: "./responses/200.AuthTokenAndCheckoutCompletionInfo.yaml" }
    200CheckPromoCode: { $ref: "./responses/200.CheckPromoCode.yaml" }
    200StripeLink: { $ref: "./responses/200.StripeLink.yaml" }
    400InvalidUserInput: { $ref: "./responses/400.InvalidUserInput.yaml" }
    401AuthenticationRequired: { $ref: "./responses/401.AuthenticationRequired.yaml" }
    402PaymentRequired: { $ref: "./responses/402.PaymentRequired.yaml" }
    403Forbidden: { $ref: "./responses/403.Forbidden.yaml" }
    404ResourceNotFound: { $ref: "./responses/404.ResourceNotFound.yaml" }
    5xxInternalServerError: { $ref: "./responses/5xx.InternalServerError.yaml" }
    UnexpectedResponse: { $ref: "./responses/default.UnexpectedResponse.yaml" }
  # prettier-ignore
  schemas:
    # REQUEST-RELATED SCHEMAS:
    UserRegistrationParams: { $ref: "./schemas/UserRegistrationParams.yaml" }
    LoginParams: { $ref: "./schemas/LoginParams.yaml" }
    LoginCredentials: { $ref: "./schemas/LoginCredentials.yaml" }
    LocalLoginCredentials: { $ref: "./schemas/LoginCredentials.Local.yaml" }
    GoogleOAuthLoginCredentials: { $ref: "./schemas/LoginCredentials.GoogleOAuth.yaml" }
    GoogleIDTokenField: { $ref: "./schemas/GoogleIDTokenField.yaml" }
    UserProfileParams: { $ref: "./schemas/UserProfileParams.yaml" }
    ExpoPushTokenParam: { $ref: "./schemas/ExpoPushTokenParam.yaml" }
    # RESPONSE-RELATED SCHEMAS:
    AuthTokenResponseField: { $ref: "./schemas/AuthTokenResponseField.yaml" }
    PreFetchedUserItemsResponseField: { $ref: "./schemas/PreFetchedUserItemsResponseField.yaml" }
    PreFetchedUserItems: { $ref: "./schemas/PreFetchedUserItems.yaml" }
    Contact: { $ref: "./schemas/Contact.yaml" }
    Invoice: { $ref: "./schemas/Invoice.yaml" }
    WorkOrder: { $ref: "./schemas/WorkOrder.yaml" }
    PromoCodeInfoResponseField: { $ref: "./schemas/PromoCodeInfoResponseField.yaml" }
    PromoCodeInfo: { $ref: "./schemas/PromoCodeInfo.yaml" }
    CheckoutCompletionInfoResponseField: { $ref: "./schemas/CheckoutCompletionInfoResponseField.yaml" }
    CheckoutCompletionInfo: { $ref: "./schemas/CheckoutCompletionInfo.yaml" }
    StripeLinkResponseField: { $ref: "./schemas/StripeLinkResponseField.yaml" }
    # OTHER SCHEMAS:
    CspViolationReport: { $ref: "./schemas/CspViolationReport.yaml" }
    Error: { $ref: "./schemas/Error.yaml" }
    Location: { $ref: "./schemas/Location.yaml" }
    SubscriptionPriceName: { $ref: "./schemas/SubscriptionPriceName.yaml" }
    UserProfile: { $ref: "./schemas/UserProfile.yaml" }
    # OBJECT PROPERTIES:
    CreatedAt: { $ref: "./objectProperties/createdAt.yaml" }
    Email: { $ref: "./objectProperties/email.yaml" }
    GoogleIDToken: { $ref: "./objectProperties/googleIDToken.yaml" }
    Handle: { $ref: "./objectProperties/handle.yaml" }
    Password: { $ref: "./objectProperties/password.yaml" }
    PaymentMethodID: { $ref: "./objectProperties/paymentMethodID.yaml" }
    Phone: { $ref: "./objectProperties/phone.yaml" }
    PromoCode: { $ref: "./objectProperties/promoCode.yaml" }
    ReturnURL: { $ref: "./objectProperties/returnURL.yaml" }
    UpdatedAt: { $ref: "./objectProperties/updatedAt.yaml" }
