name: CI/CD Pipeline

on:
  workflow_dispatch:
  pull_request:
    branches: [main, next]
    paths: ["src/**/*", "package*.json"]
  push:
    branches: [main, next]
    paths: ["src/**/*", "package*.json"]

jobs:
  # TODO Add Nerdware-LLC/reusable-action-workflows/.github/workflows/node_test.yaml@main
  # once the DDB and Stripe mocks are setup for CI environment (currently local-only).
  release:
    uses: Nerdware-LLC/reusable-action-workflows/.github/workflows/release.yaml@v1.0.0
    secrets:
      SEMANTIC_RELEASE_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
  deploy:
    needs: release
    if: ${{ success() }}
    uses: Nerdware-LLC/reusable-action-workflows/.github/workflows/ecr_image_push.yaml@v1.0.0
    secrets:
      OIDC_GITHUB_ROLE_ARN: ${{ secrets.OIDC_GITHUB_ROLE_ARN }}
      AWS_ECR_PRIVATE_REPO: ${{ secrets.AWS_ECR_PRIVATE_REPO }}
      AWS_ECR_REGION: ${{ secrets.AWS_ECR_REGION }}
    permissions:
      id-token: write
      contents: read
