name: ECR Image Push
# This Action builds the fixit-api Docker image and pushes it to ECR

on:
  push:
    branches: ["main"]
  release:
    types: ["published"]

jobs:
  deploy:
    name: Build & Push
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.OIDC_GITHUB_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_ECR_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_PRIVATE_REPO }}
        run: |
          REF="${GITHUB_REF#refs/*/}" && IMAGE_TAG="${REF%/merge}"
          docker build -t $ECR_REPOSITORY/fixit-api:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY/fixit-api:$IMAGE_TAG

        # The above IMAGE_TAG value will be the variable component of the GITHUB_REF env var,
        # the value of which depends on the type of event which caused the Action to run.
        #
        #   EVENT           REF                             IMAGE_TAG
        #   branch push     refs/heads/<branch_name>        <branch_name>
        #   pr              refs/pull/<pr_number>/merge     <pr_number>
        #   release         refs/tags/<release_tag>         <release_tag>
