name: Release Workflow

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      semantic_version:
        description: "The Semantic Release version to use"
        default: "19.0.3"
        required: false
        type: string
    secrets:
      SEMANTIC_RELEASE_TOKEN:
        required: true

jobs:
  release:
    name: Release
    uses: Nerdware-LLC/reusable-action-workflows/.github/workflows/release.yaml@main
    secrets:
      SEMANTIC_RELEASE_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
