name: ECR Image Push Workflow

# This Action builds the fixit-api Docker image and pushes it to ECR

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      version-tag:
        description: |
          The version tag to use for the Docker image. If this value is
          not provided, the version will be ascertained by using the
          "version" value in a package.json file if one is present.
        required: false
        type: string
    secrets:
      OIDC_GITHUB_ROLE_ARN:
        description: "The ARN of the AWS IAM Role for the GitHub OpenID Connect provider"
        required: true
      AWS_ECR_PRIVATE_REPO:
        description: "The name of the target AWS ECR repo"
        required: true
      AWS_ECR_REGION:
        description: "The AWS region in which the target ECR repo is located"
        required: true

jobs:
  ecr_image_push:
    name: Deploy
    uses: Nerdware-LLC/reusable-action-workflows/.github/workflows/ecr_image_push.yaml@main
    secrets:
      OIDC_GITHUB_ROLE_ARN: ${{ secrets.OIDC_GITHUB_ROLE_ARN }}
      AWS_ECR_PRIVATE_REPO: ${{ secrets.AWS_ECR_PRIVATE_REPO }}
      AWS_ECR_REGION: ${{ secrets.AWS_ECR_REGION }}
    permissions:
      id-token: write
      contents: read
